[platformio]
default_envs = eb_wf03_01

[env]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_size = 4MB
board_build.ldscript = eagle.flash.4m2m.ld
board_build.flash_mode = dout
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

[env:eb_wf03_01]
lib_deps =
  knolleary/PubSubClient@^2.8

[env:eb_wf03_01_ota]
extends = env:eb_wf03_01
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}

[env:eb_wf03_01_recovery]
build_flags =
  ${env.build_flags}
  -D FIVESTAR_RECOVERY_ONLY=1

[env:eb_wf03_01_recovery_ota]
extends = env:eb_wf03_01_recovery
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}

[env:eb_wf03_01_connected_diag]
extends = env:eb_wf03_01
build_flags =
  ${env.build_flags}
  -D FIVESTAR_CONNECTED_DIAGNOSTIC=1

[env:eb_wf03_01_connected_diag_ota]
extends = env:eb_wf03_01_connected_diag
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}

[env:eb_wf03_01_pin_diag]
extends = env:eb_wf03_01
build_flags =
  ${env.build_flags}
  -D FIVESTAR_PIN_DIAGNOSTIC=1
  -D FIVESTAR_SERIAL_DEBUG=0

[env:eb_wf03_01_pin_diag_ota]
extends = env:eb_wf03_01_pin_diag
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}

[env:eb_wf03_01_pin_diag_low_power]
extends = env:eb_wf03_01_pin_diag
build_flags =
  ${env:eb_wf03_01_pin_diag.build_flags}
  -D FIVESTAR_LOW_POWER=1

[env:eb_wf03_01_pin_diag_low_power_ota]
extends = env:eb_wf03_01_pin_diag_low_power
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}

[env:eb_wf03_01_pin_diag_ultra_low_power]
extends = env:eb_wf03_01_pin_diag
board_build.f_cpu = 80000000L
build_flags =
  ${env:eb_wf03_01_pin_diag.build_flags}
  -D FIVESTAR_ULTRA_LOW_POWER=1

[env:eb_wf03_01_fast_power_monitor]
extends = env:eb_wf03_01
build_flags =
  ${env.build_flags}
  -D FIVESTAR_FAST_POWER_MONITOR=1
  -D FIVESTAR_SERIAL_DEBUG=0
