[platformio]
default_envs = eb_wf03_01

[env]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_size = 4MB
board_build.ldscript = eagle.flash.4m2m.ld
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

[env:eb_wf03_01]
lib_deps =
  knolleary/PubSubClient@^2.8

[env:eb_wf03_01_ota]
extends = env:eb_wf03_01
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}

[env:eb_wf03_01_recovery]
build_flags =
  ${env.build_flags}
  -D FIVESTAR_RECOVERY_ONLY=1

[env:eb_wf03_01_recovery_ota]
extends = env:eb_wf03_01_recovery
upload_protocol = espota
upload_port = fivestar-inverter.local
upload_flags =
  --auth=${sysenv.FIVESTAR_OTA_PASSWORD}
